[2022-12-14T12:23:49.285+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:23:44.004176+00:00 [queued]>
[2022-12-14T12:23:49.292+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:23:44.004176+00:00 [queued]>
[2022-12-14T12:23:49.293+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:23:49.293+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T12:23:49.294+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:23:49.306+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): generate_wrapped> on 2022-12-14 12:23:44.004176+00:00
[2022-12-14T12:23:49.312+0000] {standard_task_runner.py:55} INFO - Started process 27467 to run task
[2022-12-14T12:23:49.316+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weekly_wrapped_dag', 'generate_wrapped', 'manual__2022-12-14T12:23:44.004176+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/weekly_dag.py', '--cfg-path', '/tmp/tmpr9dq24qw']
[2022-12-14T12:23:49.317+0000] {standard_task_runner.py:83} INFO - Job 80: Subtask generate_wrapped
[2022-12-14T12:23:49.359+0000] {task_command.py:389} INFO - Running <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:23:44.004176+00:00 [running]> on host b92abc15fbab
[2022-12-14T12:23:49.406+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weekly_wrapped_dag
AIRFLOW_CTX_TASK_ID=generate_wrapped
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T12:23:44.004176+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-14T12:23:44.004176+00:00
[2022-12-14T12:23:49.415+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-14T12:23:49.422+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weekly_dag.py", line 47, in generate_wrapped
    print(dict(json.dumps(result)))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
[2022-12-14T12:23:49.429+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=weekly_wrapped_dag, task_id=generate_wrapped, execution_date=20221214T122344, start_date=20221214T122349, end_date=20221214T122349
[2022-12-14T12:23:49.437+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 80 for task generate_wrapped (dictionary update sequence element #0 has length 1; 2 is required; 27467)
[2022-12-14T12:23:49.450+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-14T12:23:49.470+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
